### ISSUE TITLE
RuntimeError: Legacy autograd function with non-static forward method is deprecated.

### ISSUE THREAD

**Issue by rochakjain361** [Borahb/Object-Detection-through-SSD#2]
I am facing the same issue, that I guess you have faced earlier.Can please tell me what changes you made to the code to remove this error.

Traceback (most recent call last):

  File "<ipython-input-19-96bf658efe3e>", line 100, in <module>
    frame = detect(frame, net.eval(), transform)

  File "<ipython-input-19-96bf658efe3e>", line 33, in detect
    y = net(x)

  File "C:\Users\Rochak Roopesh Jain\new\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\Rochak Roopesh Jain\Desktop\Computer_Vision_A_Z_Template_Folder\Object Detection\ssd.py", line 97, in forward
    self.priors.type(type(x.data))                  # default boxes

  File "C:\Users\Rochak Roopesh Jain\new\anaconda3\lib\site-packages\torch\autograd\function.py", line 145, in __call__
    "Legacy autograd function with non-static forward method is deprecated. "

RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

**Comment by Borahb** [comment]
No..till now I am not able to solve this issue. I am still looking into it.

**Comment by rochakjain361** [comment]
Wait a minute, then how did you get the output of video with the objects detected. Please can you tell me another way to make the code run if not to solve this issue.

**Comment by Borahb** [comment]
I guess you have updated your software..that's why you are getting a runtime error.When I was running my program till then it was not deprecated and I have been able to run it and get the output with objects detected but with less accuracy as autograd function needs to written with new style.

**Comment by rochakjain361** [comment]
Yeah but actually before the update, it was not working either so I didn't have an option. Anyways thanks for ur help.
